# Generated by Django 2.1.2 on 2020-01-05 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '小園家蔵書トラン', 'verbose_name_plural': '小園家蔵書トラン'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_10',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_5',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_6',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_7',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_8',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_9',
        ),
        migrations.AddField(
            model_name='item',
            name='book_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='本の名前'),
        ),
        migrations.AddField(
            model_name='item',
            name='author_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='著者'),
        ),
        migrations.AddField(
            model_name='item',
            name='read_status',
            field=models.IntegerField(blank=True, choices=[(1, '読んだけどまた読みたい'), (2, '読んだ'), (3, '読んでない')], null=True, verbose_name='ステータス'),
        ),
        migrations.AddField(
            model_name='item',
            name='read_reason',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='読みたい理由'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_wonder',
            field=models.BooleanField(default=0, verbose_name='関心が高い'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_10', to=settings.AUTH_USER_MODEL, verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='item',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='読み始め'),
        ),
        migrations.AddField(
            model_name='item',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='読み終わり'),
        ),
        migrations.AddField(
            model_name='item',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='書評'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='登録時間'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CreatedBy', to=settings.AUTH_USER_MODEL, verbose_name='登録ユーザー'),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='最終更新時間'),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UpdatedBy', to=settings.AUTH_USER_MODEL, verbose_name='最終更新ユーザー'),
        ),
    ]
