# Generated by Django 2.1.2 on 2020-01-05 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_auto_20200106_0458'),
        ('app', '0002_auto_20200106_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='本の名前')),
                ('author_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='著者')),
                ('read_status', models.IntegerField(blank=True, choices=[(1, '読んだけどまた読みたい'), (2, '読んだ'), (3, '読んでない')], null=True, verbose_name='ステータス')),
                ('read_reason', models.CharField(blank=True, max_length=20, null=True, verbose_name='読みたい理由')),
                ('is_wonder', models.BooleanField(verbose_name='関心が高い')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='読み始め')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='読み終わり')),
                ('review', models.TextField(blank=True, null=True, verbose_name='書評')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='登録時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='最終更新時間')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='category.Category', verbose_name='カテゴリ')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CreatedBy', to=settings.AUTH_USER_MODEL, verbose_name='登録ユーザー')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UpdatedBy', to=settings.AUTH_USER_MODEL, verbose_name='最終更新ユーザー')),
            ],
            options={
                'verbose_name': '小園家蔵書トラン',
                'verbose_name_plural': '小園家蔵書トラン',
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
